cambios en repl para comando reload
uqbar-project/wollok-ts-cli pull request #22
Opened 2022-06-29 12:29 UTC by julimr

Fixes #19 
Co-Authored-By: Fernando Romero <70177008+FerRomMu@users.noreply.github.com>

2022-06-29 14:13 UTC, asanzo commented on src/commands/repl.ts
> +const config: Partial<ReplConfig> = {}
¿Quizás `config` debería llamarse `replState`?

2022-06-29 14:27 UTC, asanzo commented
@nscarcella te pedimos un PR Review, metimos un estado global para poder recordar los imports hechos y tener acceso a varios objetos entre reloads. Gracias :cat: :heart: :heart_eyes: :dancers: :man_dancing:

2022-06-29 23:25 UTC, nscarcella commented on src/commands/repl.ts
> +const config: Partial<ReplConfig> = {}
Para mi no hace falta la parte de "repl". Estamos en el repl, todo es repl algo. Sobre si state o config me da igual, pero eligan uno y usenlo en el tipo y la referencia así evitamos confusiones

2022-06-30 00:10 UTC, nscarcella requested changes

2022-06-30 00:10 UTC, nscarcella commented on src/commands/repl.ts
> +  log(`Initializing Wollok REPL ${config.autoImportPath ? `for file ${valueDescription(config.autoImportPath)} ` : ''}on ${valueDescription(config.options!.project)}`)
Estamos seguros de que queremos loguear esto cada vez que se hace reload @asanzo? Capaz puede sacarse afuera de la función y llamarse sólo la primera vez. O bueno, capaz sí hay mostrarlo siempre. No sé.

2022-06-30 00:10 UTC, nscarcella commented on src/commands/repl.ts
>    .action(() =>
Una de dos: Podemos eliminar la lambda que creamos inline acá y llamar directamente a `.action(reload)` o eliminar la función auxiliar `reload` y poner el código acá.
Yo personalmente prefiero la segunda opción. `reload` no va a volver a llamarse en ningún lado, al pedo tener una función separada que hay que scrollear para ver qué hace (además, estamos alejando la definición del string que documenta lo que hace 2 lineas más arriba).

2022-06-30 00:10 UTC, nscarcella commented on src/index.ts
> +  .version(process.env.npm_package_version ?? 'unknown')
No creo que haga falta el `??`, esto siempre debería estar presente.

2022-06-30 01:32 UTC, asanzo reviewed
GRACIAS @nscarcella !!!
@julimr @FerRomMu miren cómo Nico nos propone evitar guardar el estado global sencillamente jugando con los contextos de las funciones. Me dijo que el viernes se pasa y nos refactoriza en la carita. 

De todas formas, si quieren intentarlo antes, bienvenides sean. Y el viernes lo cerramos bien con Nico.

¡Nos vemos el viernes!

2022-06-30 01:32 UTC, asanzo commented on src/commands/repl.ts
>    .action(() =>
Seh, re. A la verga el reload.

2022-06-30 01:32 UTC, asanzo commented on src/commands/repl.ts
> +  log(`Initializing Wollok REPL ${config.autoImportPath ? `for file ${valueDescription(config.autoImportPath)} ` : ''}on ${valueDescription(config.options!.project)}`)
Me parece que un comando tiene que tener feedback de cuando se realiza. Siempre que haya un feedback que diga "fue todo bien" estoy contento.

De hecho, acabo de darme cuenta que metimos un bug:
![image](https://user-images.githubusercontent.com/5421992/176571426-dddc7873-6a10-48e9-9578-08d17eb964e8.png)

Y ahí me parece que nada es necesario salvo la última línea verde que es la que posta quiero ver.

2022-06-30 01:32 UTC, asanzo commented on src/index.ts
> +  .version(process.env.npm_package_version ?? 'unknown')
A Fer le pasó que con las pruebas de electron-builder hubo momentos en los que no existía. De hecho, me marcó el typo este que estamos corrigiendo acá porque le saltó.

2022-06-30 01:32 UTC, asanzo commented on src/commands/repl.ts
> +async function load(){
Dalep, sí, load es re mal nombre.

2022-06-30 01:32 UTC, asanzo commented on src/commands/repl.ts
> +const config: Partial<ReplConfig> = {}
Bueno, este es el comentario que me parece más interesante. Todo lo que decís es cierto. Pero la función default empieza, parsea todo, levanta el repl loco de readline, y listo, termina. Hay que traerse la inicialización del commandHandler al contexto de la función default para poderle dejar todas las cosas que necesita en la mano y así no necesitar guardar el estado global.

O sea, también sacar el commandHandler del estado global. ¿No? Y que forme parte del contexto de la función default.

No lo había visto. GRACIAS!!

2022-07-01 19:19 UTC, asanzo commented
Bueno, acabamos de hacer una primera iteración @nscarcella si querés chusmearla. Igual falta.

TODO:

- [ ] Al hacer :r estas líneas no deberían aparecer:

![image](https://user-images.githubusercontent.com/5421992/176956905-02e815ec-0ea0-4a92-a5f9-730d631224ef.png)


- [ ] Ahora los errores en las funciones auxiliares hay que ver cómo reportarlos de forma bonita en consola (comparar antes y después en la imagen):

Antes:
![image](https://user-images.githubusercontent.com/5421992/176956720-d51868b3-25f8-446b-a684-9d112633a036.png)

Ahora:
![image](https://user-images.githubusercontent.com/5421992/176956448-fa56627c-7700-4693-ad00-9e558eea9c29.png)

2022-07-01 19:20 UTC, asanzo commented
Sobre el segundo punto, quizás teniendo un logger y seteando un log level al iniciar el cli???

2022-07-05 22:01 UTC, FerRomMu commented
> * [ ]  Ahora los errores en las funciones auxiliares hay que ver cómo reportarlos de forma bonita en consola (comparar antes y después en la imagen):
> 
> Antes: ![image](https://user-images.githubusercontent.com/5421992/176956720-d51868b3-25f8-446b-a684-9d112633a036.png)
> 
> Ahora: ![image](https://user-images.githubusercontent.com/5421992/176956448-fa56627c-7700-4693-ad00-9e558eea9c29.png)

Posible solución en #24 .

2022-07-06 12:55 UTC, asanzo commented
Solución al otro todo en #23 .

@PalumboN si tenés ganas vos tmb podés revisar este PR (y los otros dos) para ver si estamos orientades, no es tan necesario que sea únicamente Nico. Gracias <3

2022-07-06 23:10 UTC, nscarcella commented on src/commands/repl.ts
> +async function initializeInterpreter(autoImportPath: string|undefined, { project, skipValidations }: Options): Promise<{ imports: Import[], interpreter: Interpreter}> {
Lo típico en estos casos en dónde una función retorna más de una cosa con tipos únicos es hacerla retornar una **tupla** en lugar de un objeto (en este caso, el tipo sería `[Interpreter, Import[]]` eso, utilizado con deconstrucción y spread, te evita tener esas colisiones de nombre incomodas como la de la linea 29, dónde querés setear algo que se llama igual que un campo de lo que recibís, entonces no lo podés deconstruir fácil.

2022-07-06 23:12 UTC, nscarcella commented on src/commands/repl.ts
> +function defineCommands( autoImportPath: string | undefined, options: Options, setInterpreter: (o: {interpreter: Interpreter, imports: Import[]}) => void ): Command {
Acá sería mejor (sobre todo si me dan bola con lo de retornar una tupla en la otra función) recibir dos parámetros separados en lugar de un objeto `o` en el callback. También estaría bueno buscarle un nombre mejor que `setInterpreter`, siendo que se lo usa para setear más de una cosa y además causar un efecto.

2022-07-06 23:13 UTC, nscarcella approved these changes
Bueno, dejé un par de comentarios menores, pero el código ya se ve mucho mejor.

2022-07-08 17:49 UTC, merged